// <auto-generated />
namespace bookstore_Management.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class FixStaffEnumMapping : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixStaffEnumMapping));
        
        string IMigrationMetadata.Id
        {
            get { return "202511270825429_FixStaffEnumMapping"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
